### ISSUE TITLE
Missing "in" on readonly struct method parameters?

### ISSUE THREAD

**Issue by bboyle1234** [AArnott/Nerdbank.Streams#175]
Hi Andrew, 
I noticed that most readonly struct method parameters are not passed using "in".
Is there a reason for this?

**Comment by AArnott** [comment]
Not really. It requires more thought to add the `in` modifier and I almost never go to the trouble to consider it. 

Some considerations:
1. Adding the `in` modifier is a binary API breaking change, so adding it to public API is not an option once the API has shipped.
1. Adding `in` passes the struct as a pointer instead of by value, so to see any perf benefit the struct must exceed the size of a pointer (>8 bytes on 64-bit processes).
1. Even for large structs, the perf benefit is very small, so only in the hottest perf paths is it even interesting to consider. Nerdbank.Streams doesn't have such paths as far as I know.

In contrast, the MessagePack-CSharp project that I contribute a lot to _does_ use `in` on some of its methods for the `ReadOnlySequence<T>` struct. That struct is quite large and a great deal of MessagePack is perf critical.
