### ISSUE TITLE
Unusual use of Sequence

### ISSUE THREAD

**Issue by bboyle1234** [AArnott/Nerdbank.Streams#295]
Hi  Andrew,
I just wanted to show you this unusual use of the `Sequence<T>` object.
I had no easy way (that I know of) to create a `ReadOnlySequence` from a span, which is the real need here, and so I just used a span from the sequence and used the sequence.AsReadOnlySequence property:

![image](https://user-images.githubusercontent.com/1445862/103194165-bb5de600-48ac-11eb-8d83-2a255011ad4e.png)

**Comment by AArnott** [comment]
This pattern isn't supported, and could break in the future. The only legit time to access a span while writing is between acquiring the memory and calling `Advance`. As it is, you`re depending on an implementation detail of `Sequence<T>`.

Any "upgrade" of a `Span<T>` to a `ReadOnlySequence<T>` would involve a memory copy, since while you can get a span from a memory, you cannot get a memory from a span, and ReadOnlySequence is necessarily based on `Memory<T>`.

It also looks like you intend for the ReadOnlySequences to outlive an individual iteration of your `for` loop. But aren't you writing to the same location on the span each time? That will overwrite the same memory that is in use from a previous iteration.
Then, when you recycle the `Sequence<T>` itself, that memory will again get used for something else, causing apparent memory corruption in your Store.

Instead, why not allocate a unique `byte[]` for each memory you want to keep around, write to its span (using AsSpan), then use `new ReadOnlySequence<byte>(array)` to create your final object?

**Comment by bboyle1234** [comment]
> This pattern isn't supported, and could break in the future. The only legit time to access a span while writing is between acquiring the memory and calling `Advance`. As it is, you`re depending on an implementation detail of `Sequence`.

Good point.

> Any "upgrade" of a `Span<T>` to a `ReadOnlySequence<T>` would involve a memory copy, since while you can get a span from a memory, you cannot get a memory from a span, and ReadOnlySequence is necessarily based on `Memory<T>`.
> 
> It also looks like you intend for the ReadOnlySequences to outlive an individual iteration of your `for` loop. But aren't you writing to the same location on the span each time? That will overwrite the same memory that is in use from a previous iteration.
> Then, when you recycle the `Sequence<T>` itself, that memory will again get used for something else, causing apparent memory corruption in your Store.

`Store[tileId].Set()` involves a memory copy, so we are not expecting the ReadOnlySequences to outlive an individual iteration of the for loop. Do you think there's a better way to name the method so this is more obvious? 

> Instead, why not allocate a unique `byte[]` for each memory you want to keep around, write to its span (using AsSpan), then use `new ReadOnlySequence<byte>(array)` to create your final object?

It's on a hotpath - this method is called thousands of times per second, as the app scales, and it needs to be allocation-free.

Thanks for your feedback Andrew. With the brainstorming, I've decided to make the `Store[tileId].Set(ReadOnlySequence<byte> entireRawImageData) method take the entire raw data image and pick out its own tile data, thereby completely eliminating the interstial buffer sequence seen in that method. It will be much more efficient.
