### ISSUE TITLE
MultiplexingStream received "Offer" before subscribe "ChannelOffered" event

### ISSUE THREAD

**Issue by nigma143** [AArnott/Nerdbank.Streams#345]
MultiplexingStream received "Offer" before subscribe "ChannelOffered" event because readstream loop started in MultiplexingStream constructor

var multiplexingStream = await MultiplexingStream.CreateAsync(...) <-- here received an offer from a client
multiplexingStream.ChannelOffered += this.ChannelOffered;

**Comment by AArnott** [comment]
Ooh, bummer. You're right. In StreamJsonRpc we avoid this problem by requiring the user to call `StartListening` after they hook up their event handlers if they used the constructor directly.
Since we can't make that behaviorally breaking change, we'll have to add another overload that does not start reading from the stream till you call a `Start` method.
